### ISSUE TITLE
App closed

### ISSUE THREAD

**Issue by hectorevil86** [shirokumacode/overwatch-omnic-rewards#11]
Try with OWL streams today. But the tray icon closes without any explanation.

**Comment by shirokumacode** [comment]
Blizzard changed the endpoints for tracking the streams in this new season and added a few minor changes. I have a patch in the works that fixes the issue. Expect a new release in the next hour if all goes well. Meanwhile watch on the overwatchleague.com.

**Comment by hectorevil86** [comment]
Thank you!

**Comment by shirokumacode** [comment]
Fixed in version 1.3
