### ISSUE TITLE
The counter was still running even though there was no online stream.

### ISSUE THREAD

**Issue by hectorevil86** [shirokumacode/overwatch-omnic-rewards#13]
I will test it again today to make sure it does not fail. 
But last night the program was still counting hours even though the stream was finished.

**Comment by shirokumacode** [comment]
This seems to be a persistent issue in this season of OWL. I'll create a workaround for this, if I have time, on the next release of the app (I'll make the app periodically check if the youtube video panel on overwatchleague.com disappears; if it does it will assume the current stream has ended).

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
