### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by Juice805** [shirokumacode/overwatch-omnic-rewards#14]
This tool has been very helpful, thanks for work!

It would be great if it had a command line only mode. It would make it very easy to spawn multiple sessions with screen, docker containers, etc.

For the most part, I don't need the UI.

**Comment by shirokumacode** [comment]
The app already has a command line only mode (a person in the discussions asked for it). Run the app with the "-c" or "--cli" argument. It will not need a system tray to work, ideal to be run on a server or anything that doesn't have a display server. However you need to make a _config.json_ file manually or copy the one you already have. You can also have multiple config/history files in the same directory and pass them to the app using the argument "-cf" or "--config" or "-hf" or "--history". Use "-h" or "--help" to see all the possible arguments.

**Comment by Juice805** [comment]
Thanks! I had done a search through the issues and couldnt find anything. I'll give it a shot

**Comment by shirokumacode** [comment]
Those libGL imports seem strange. Those are done by Qt itself or my. Not sure if a bug or intended behaviour. I make use of QCoreApplication when in CLI mode which is recommended for headless non-GUI apps.
When I introduced the CLI mode I tested it with a docker image of Ubuntu Server and it run fine. I guess Ubuntu Server includes libGL.
I'll investigate this when I have time and possibly open a bug report on Qt.

**Comment by Juice805** [comment]
To clarify the docker image I used was `debian:stable-slim`. The full Debian probably has it, although I hope to use the slim, as this isn't a heavy application.

Thanks for your work!

**Comment by a1d4r** [comment]
I opened a pull request #16 with Dockerfile. Also, I pushed the image to Dockerhub, so you can test if it works.
`docker run -d -e ACCOUNT_ID=123456789 a1d4r/overwatch-omnic-rewards:latest`
Put ID of your Blizzard account instead of 123456789

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
