### ISSUE TITLE
OWL Live but program doesn't detect it.

### ISSUE THREAD

**Issue by KurtzPT** [shirokumacode/overwatch-omnic-rewards#15]
```
INFO:settings:Settings loaded
INFO:__main__:CLI Mode enabled
INFO:checkviewer:Starting checkviewer
INFO:checkviewer:Checking if live
INFO:checkviewer:OWL is Live
INFO:checkviewer:Start Watching
INFO:checkviewer:Sending sentinel packets
WARNING:checkviewer:Watched for 0 minutes. Stream has probably ended
```

[YouTube Stream](https://www.youtube.com/watch?v=aMoOfSbN0FE)

Seems an encore stream, just letting you know.

**Comment by shirokumacode** [comment]
Today has been a mess for watching the stream on overwatchleague.com. Blizzard's tracking endpoints have been a complete mess. The behaviour you describe is basically the same as the "green circle" disappearing, which has been happening though the day whether you use the app or watch in the browser. Basically Blizzard's tracking respond the stream has ended and to stop tracking when the stream is still running. That and the panel for the youtube video on overwatchleague.com has been randomly disappearing.
This app basically emulates watching though overwatchleague.com. I can't fix Blizzard's stuff when they break unfortunately.

**Comment by Kureka** [comment]
Is there anyway to emulates watching through Youtube instead? Since it's more stable than OWL website.

**Comment by shirokumacode** [comment]
I don't how the exact method Youtube uses to track your watch time using their "Rewards" program. I assume it is deeply tied to Youtube internals and not trivial to reverse engineer. But it is possible to emulate a headless browser that would play the video on Youtube. That is significantly more complicated, would imply storing logins (plus you need to link accounts) and would be extremely heavy on resources (as you would probably still need to decode the video). If anyone knows more about Youtube rewards internals, or an easy way to do this contact me. 
The mechanism for tracking your watch time on overwatchleague.com is so simple and light that I am amazed Blizzard managed to somehow mess it up.

I am not sure of this but it is likely these problems on Blizzard tracking endpoints might spillover even when you watch on Youtube. Youtube might track your watch time perfectly down to the second (it is Youtube we are talking about) but this must be sent to Blizzard tracking servers and synced with your time watched on overwatchleague.com to avoid giving double tokens. Blizzard's tracking endpoints right now are assuming the stream has ended (or as the server responds "not able to track/earn tokens") when it hasn't, making some time in the middle of it "untrackable". This can spillover when syncing the watch time, depending on how they implemented earning tokens/tracking time/syncing watch time.

**Comment by Kureka** [comment]
I don't mind if it's headless browser or chrome/firefox plugin and need to login YT first + decode the video with lowest resolution, as long as it will autoplay the stream when OWL goes live and stop after the live stream ended.

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
