### ISSUE TITLE
Termux support 

### ISSUE THREAD

**Issue by Sergo1217** [shirokumacode/overwatch-omnic-rewards#18]
![Screenshot_2022-05-28-03-41-23-426_com termux](https://user-images.githubusercontent.com/16447886/170802995-2ef859b5-9a2c-4825-a7e3-aee2542dc513.jpg)

**Comment by github59173** [comment]
Inb4 android app 👀. Thought about it for a while. Haven't really looked into making it an app yet though.

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
