### ISSUE TITLE
Problems getting tokens

### ISSUE THREAD

**Issue by NotNumb** [shirokumacode/overwatch-omnic-rewards#26]
Hello! After changing the region, tokens stopped coming. Reinstalling the application did not help. Also, the id did not change after changing the region, but the tokens do not come to the account.

**Comment by shirokumacode** [comment]
Did you change to a region that is not eligible for tokens? You can check the [Overwatch League Perks Official Rules here](https://assets.blz-contentstack.com/v3/assets/blt321317473c90505c/blt80d7af66046aa1d5/62606bccf15a7f436ba45072/2022_OWL_Perks_Rules_enUS.pdf)

> Legal residents of Cuba, Iran, the Democratic People’s Republic of Korea, Sudan, Crimea, the so-called Donetsk People’s Republic, and so-called Luhansk People’s Republic, and Syria, and other countries where restricted or prohibited by law are not eligible for the Promotion. Legal residents of the People’s Republic of China (which for the purposes of these rules, excludes Hong Kong, Macau and Taiwan) and Japan are also not eligible for the Promotion. 

Also not sure if Russia is able to earn tokens, given that Blizzard, as far as know, stopped sales there.

**Comment by NotNumb** [comment]
Until that time, I had the region Russia (it was just convenient), but recently I changed it and I started having problems getting tokens, also I don’t live in the territories of Ukraine, which are banned by Blizzard.

**Comment by shirokumacode** [comment]
If you are in a eligible country/region, your account is in good standing and you are over 13yo you should earn tokens without a problem. Also if the app is reporting that it is "watching" and is tracking minutes it means it has successfully sent your watch time to Blizzard's tracking endpoints and received an "ok" as response (this is performed every minute). 

Although the app performs the same exact thing as watching on [https://overwatchleague.com/en-us/](https://overwatchleague.com/en-us/), I would try to watch an hour there to completely confirm you are not able to earn tokens and then contact Blizzard support. This is most likely a problem on Blizzard's end, especially when it only started after changing regions.

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
