### ISSUE TITLE
Didn't get Contenders skins

### ISSUE THREAD

**Issue by brusvv** [shirokumacode/overwatch-omnic-rewards#28]
I watched enough, but still haven't skin fot Tracer. That seems like something doesn't work.
![image](https://user-images.githubusercontent.com/55412131/180891493-e1c77ec5-b0f6-42be-9b93-216f5ed4c6cb.png)
P.S. I'm getting OWL tokens, but not the skins.
I heard that Contders site might have a problem and only people, who watched YouTube, got the skins.

**Comment by shirokumacode** [comment]
I edited the readme earlier today and posted a [section about this right at the top](https://github.com/shirokumacode/overwatch-omnic-rewards#owc). I also put every mention of Contenders skins with an asterisk linking to that section.

Blizzard changed the rules of OWC rewards for this season (you can read them [here](https://assets.blz-contentstack.com/v3/assets/blt321317473c90505c/blta6154001578bb2c6/62cf20652fdd1011027e5e83/2022ContendersViewIncentivesLEGALFINAL.pdf)) and now you can't earn contenders skins when watching on [https://overwatchleague.com/en-us/contenders](https://overwatchleague.com/en-us/contenders). Only Youtube is able to earn Contenders skins now. This app emulates watching on OWC website, making it impossible to earn skins now. 

This was a half-assed and braindead decision by Blizzard as they didn't even bother removing the rewards banner on their own website, inducing users to think they are getting skins when they are not. Their tracking endpoints still work as they did before and still track your Contenders watch time on the OWC website. The OWC website even got the same new changes for this 2022 season that the OWL website also received for the watch time tracking mechanism.

**Comment by brusvv** [comment]
Okay, thanks for the info. It would be nice if you'll add in the future the ability to farm skins via YouTube for trusting users.

**Comment by nicissimo97** [comment]
I'm afraid it's gonna happen for OWL as well. They must be using OWC as a test ground

**Comment by aquilonem** [comment]
> I'm afraid it's gonna happen for OWL as well. They must be using OWC as a test ground

Yes, me too.


> Okay, thanks for the info. It would be nice if you'll add in the future the ability to farm skins via YouTube for trusting users.

That would be great tbh. Sometimes Blizzard makes stupid decisions

**Comment by Aghneel** [comment]
When you say impossible, does that mean there is no way to track youtube live just like the ow website with api?

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
