### ISSUE TITLE
How to run into VPS, Ubuntu

### ISSUE THREAD

**Issue by Kelthic** [shirokumacode/overwatch-omnic-rewards#30]
I wanna run that app into Ubuntu on my VPS server. But have no idea how to do that. Any help?

**Comment by catalpaaa** [comment]
if you just want to run it raw with headless mode:
`python /home/catalpa/nas/program/overwatch-omnic-rewards/app.py -c --config your-config-file`

or you can use nohup to run it with background:
`nohup python /home/catalpa/nas/program/overwatch-omnic-rewards/app.py -c --config your-config-file >/dev/null 2>&1 &`

config file example:
`{
    "account": "your account id",
    "owl": true,
    "owc": true,
    "middle_click": "open_owl_owc",
    "left_click": "context_menu",
    "min_check": 5,
    "force_track": false
}`

**Comment by catalpaaa** [comment]
if you just want to run it raw with headless mode:
`python /path-to/overwatch-omnic-rewards/app.py -c --config your-config-file`

or you can use nohup to run it in background:
`nohup python /path-to/overwatch-omnic-rewards/app.py -c --config your-config-file >/dev/null 2>&1 &`

config file example:
`{ "account": "your account id", "owl": true, "owc": true, "middle_click": "open_owl_owc", "left_click": "context_menu", "min_check": 5, "force_track": false }`

**Comment by Kelthic** [comment]
> if you just want to run it raw with headless mode:
> `python /path-to/overwatch-omnic-rewards/app.py -c --config your-config-file`
> 
> or you can use nohup to run it in background:
> `nohup python /path-to/overwatch-omnic-rewards/app.py -c --config your-config-file &`
> 
> config file example:
> `{ "account": "your account id", "owl": true, "owc": true, "middle_click": "open_owl_owc", "left_click": "context_menu", "min_check": 5, "force_track": false }`

Damn. It easy enough, huh? I stupid or something. I appreciate your answer!

**Comment by shirokumacode** [comment]
Closed issue due to archiving repository
