### ISSUE TITLE
Didn't get OWL tokens

### ISSUE THREAD

**Issue by Amokow** [shirokumacode/overwatch-omnic-rewards#32]
The program is always launched. The computer does not turn off. Today and yesterday the broadcasts did not give tokens. Maybe it broke like a contender skin? Please check it.

**Comment by aquilonem** [comment]
Same problem. The program is always launched and PC never turn off.

**Comment by Slightlyxz** [comment]
Can confirm, seems like they switched to the same system as contenders now.

**Comment by shirokumacode** [comment]
There are lots of people reporting not receiving tokens this week and even the new Contenders skins on the official forum, even when watching on Youtube. I also haven't received anything yet. Blizzard probably screwed up something as usual. My guess would be the new account merger introduced something that broke the rewards system. Nothing I can do here given that everything appears normal and no rewards rules were changed.

**Comment by aquilonem** [comment]
Sad stuff. So we shall wait then.

**Comment by Slightlyxz** [comment]
The following message is being posted in youtube chat by their nightbot now: ‘‘We are aware of an issue affecting the Overwatch League Perks system. All viewers with linked accounts who have watched the YouTube Broadcast this weekend will receive their drops by Tuesday 8/23’’

**Comment by github59173** [comment]
> 

Subtle way of saying watch the official YouTube stream if you want drops like contenders. *Sadness*

**Comment by shirokumacode** [comment]
Delayed tokens are now starting to arrive based on the recent posts on the forum. I also got mine and didn't watch any OWL on Youtube. Please check if you also got them

**Comment by Amokow** [comment]
I also received 140 tokens. I looked from the program. I hope it will always be so.

**Comment by shirokumacode** [comment]
Great to hear that! I'll be closing the issue for now
