### ISSUE TITLE
Seems to have officially stopped working today

### ISSUE THREAD

**Issue by ANaPhOrAX** [shirokumacode/overwatch-omnic-rewards#35]
For the past few days it's already been a bit hit or miss with it intermittently not recognizing the stream being live, but as of today it does seem like it fully broke. I'm getting "OWL/OWC Page incorrectly formatted/error", so I think they changed something

**Comment by shirokumacode** [comment]
The app has been working for the past month and will most likely continuing to work for the rest of the 2022 OWL Season. Sometimes overwatchleague.com has some problems, like broken or missing video panel on the page which triggers an error on the app. This has been extremely common on this season. Nothing I can do about that.
