### ISSUE TITLE
Seems to not track anymore

### ISSUE THREAD

**Issue by wzGCU** [shirokumacode/overwatch-omnic-rewards#36]
I just discovered that the current livestream is not tracked by the app.  It says 'Not live - wait X minutes for check', but the stream is on and the green circle appears if you watch it on the website (https://overwatchleague.com/en-us/)

Wondering if they changed something

**Comment by shirokumacode** [comment]
Sometimes the video panel disappears momentarily from the overwatchleague.com page, you have to be lucky to catch it. When the app scanned the page it didn't get the video panel (thus thinking it is not live). This has been a new problem in this season. Wait a minute and perform a check now or just wait for the next scan.
