### ISSUE TITLE
how does it work without login?

### ISSUE THREAD

**Issue by TeddJohnson** [shirokumacode/overwatch-omnic-rewards#8]
the features list "No Login Required" but it would have to login to know which account to give tokens to I assume?

**Comment by TeddJohnson** [comment]
took about 2 minutes, but I figured it out.

you give it a UserID and that's how it attributes the "watch time". thx

**Comment by shirokumacode** [comment]
Yep that's it. It is answered in Readme -> FAQ -> "What does it need?". Should take less than a min to get your userID.
Also I have some images of the app in the repository that illustrate the account setup dialog (it has the instructions to get the your userID) -> https://github.com/shirokumacode/overwatch-omnic-rewards/blob/main/images/account.png
Asking/storing logins is kinda risky, I'm glad the userID is the only thing that is needed.
